const product = [
    {
    id: 1,
    title: "The Aura",
    author: "Putri Febrianti",
    year: 2024,
    description: "The 'Aura' Desain premium tenun yang sangat nyaman untuk pemakaian sepanjang hari. Suara murni dengan tampilan stylish dan earthy. Kenyamanan tanpa batas.",
    imgSrc: "https://plus.unsplash.com/premium_photo-1679513691474-73102089c117?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aGVhZHBob25lc3xlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 2,
    title: "The Gamer Pro X",
    author: "Aditya Febriadi",
    year: 2023,
    description: "The 'Gamer Pro X' Audio eSports-grade dengan nirkabel ultra-low latency. Dilengkapi mikrofon noise-cancelling yang dapat dilepas. Keunggulan kompetitif Anda.",
    imgSrc: "https://cdn.head-acoustics.com/_processed_/2/8/csm_CL_II.1_c272319049.jpg",
  },
  {
    id: 3,
    title: "The ZenFlow",
    author: "Syafa Khairunizza",
    year: 2024,
    description: "The 'ZenFlow' Fitur Active Noise Cancellation (ANC) terdepan di industri. Ringan dan memiliki baterai 40 jam. Sempurna untuk fokus tanpa gangguan.",
    imgSrc: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8aGVhZHBob25lc3xlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 4,
    title: "The Commuter Lite",
    author: "Putri Febrianti",
    year: 2022,
    description: "The 'Commuter Lite' Dibuat untuk perjalanan harian. Sangat ringan, dapat dilipat, dan tahan air IPX4. Nikmati bass kuat dalam paket yang ringkas dan portable.",
    imgSrc: "https://images.unsplash.com/photo-1505740106531-4243f3831c78?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 5,
    title: "The Studio Reference",
    author: "Aditya Febriadi",
    year: 2021,
    description: "The 'Studio Reference' Menggunakan planar magnetic drivers untuk suara yang sangat akurat dan uncolored. Audio berkualitas studio bagi audiophile dan produser.",
    imgSrc: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8aGVhZHBob25lc3xlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 6,
    title: "The Bold Beat",
    author: "Syafa Khairunizza",
    year: 2023,
    description: "The 'Bold Beat' Bass ekstra menggelegar yang memacu semangat Anda. Tampilan dua warna yang mencolok dengan desain yang secure untuk gaya hidup aktif.",
    imgSrc: "https://images.unsplash.com/photo-1700087151960-178ea946e608?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDN8fHxlbnwwfHx8fHw%3D",
  },
  {
    id: 7,
    title: "The Eternity",
    author: "Putri Febrianti",
    year: 2024,
    description: "The 'Eternity' Baterai revolusioner dengan 70+ jam pemutaran non-stop. Jangkauan Bluetooth diperluas. Kebebasan nirkabel sejati tanpa perlu sering mengisi daya.",
    imgSrc: "https://images.unsplash.com/photo-1679210208075-e70610a78080?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 8,
    title: "The Retro Vibe",
    author: "Aditya Febriadi",
    year: 2022,
    description: "The 'Retro Vibe' Estetika klasik dengan bingkai logam dan earpad beludru. Menggabungkan gaya vintage dengan teknologi Bluetooth 5.0 yang jernih.",
    imgSrc: "https://images.unsplash.com/photo-1737291937135-3a0fcb5e0c44?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D",
  },
  {
    id: 9,
    title: "The Fitness Endurance",
    author: "Syafa Khairunizza",
    year: 2023,
    description: "The 'Fitness Endurance' Direkayasa untuk aktivitas intens. Tahan air penuh (IPX7) dengan earpad yang tetap dingin. Rekan workout paling andal yang tidak akan lepas.",
    imgSrc: "https://images.unsplash.com/photo-1655628143766-172ca2198096?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHx8",
  },
];

export default product;